# Generated by Django 5.2.7 on 2026-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the title of the notice (e.g., 'Exam Schedule 2025')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional: Add a brief description of the notice')),
                ('pdf_file', models.FileField(help_text='Upload the notice PDF file', upload_to='notices/')),
                ('published_date', models.DateField(auto_now_add=True, help_text='Automatically set when the notice is created')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this notice from the website')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date'],
            },
        ),
    ]
