# Generated by Django 5.2.7 on 2026-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for this visit count', unique=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='Total page loads on this date')),
            ],
            options={
                'verbose_name': 'Daily Visit Count',
                'verbose_name_plural': 'Daily Visit Counts',
                'ordering': ['-date'],
            },
        ),
    ]
