# Generated by Django 5.2.7 on 2026-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_dailyvisitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter full name (e.g., 'Fr. Joshua' or 'Mr. Dipankar Holder')", max_length=150)),
                ('designation', models.CharField(choices=[('ADMIN_PR', 'Principal'), ('ADMIN_VP', 'Vice Principal'), ('TEACHER', 'Teaching Staff'), ('OFFICE', 'Non-Teaching / Support Staff')], default='TEACHER', help_text='Select their official rank layout category', max_length=40)),
                ('subject_or_role', models.CharField(help_text="Enter role or subjects (e.g., 'Computer Science & Vocational Education')", max_length=150)),
                ('photo', models.ImageField(blank=True, help_text='Optional: Upload a square portrait photo', null=True, upload_to='faculty_photos/')),
                ('sort_order', models.PositiveIntegerField(default=10, help_text='Lower values appear first on the webpage layout (e.g., set Principal to 1)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this instead of deleting if the staff member is temporarily on leave')),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
